# Generated by Django 5.2.6 on 2025-12-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Жарнама', 'verbose_name_plural': 'Жарнамалар'},
        ),
        migrations.AlterModelOptions(
            name='adimage',
            options={'verbose_name': 'Жарнама суреті', 'verbose_name_plural': 'Жарнама суреттері'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категориялар'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Қала', 'verbose_name_plural': 'Қалалар'},
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Мекен-жай'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Қала'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Компания аты'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Қала'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Жарияланды'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Көрулер'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.ad', verbose_name='Жарнама'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ads/', verbose_name='Сурет'),
        ),
    ]
